-- MySQL Script generated by MySQL Workbench
-- Fri Nov  2 22:10:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BdColchoneria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BdColchoneria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BdColchoneria` DEFAULT CHARACTER SET utf8 ;
USE `BdColchoneria` ;

-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_Grupo_de_Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_Grupo_de_Productos` (
  `PK_Codigo_Grupo_de_Productos` INT NOT NULL,
  `Nombre_de_Grupo_de_Productos` VARCHAR(45) NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`PK_Codigo_Grupo_de_Productos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_Modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_Modelo` (
  `PK_id_modelo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) NOT NULL,
  `estatus` INT NOT NULL,
  PRIMARY KEY (`PK_id_modelo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_unidaddemedidabase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_unidaddemedidabase` (
  `PK_CodigoDeUnidadDeMedidaBase` INT NOT NULL,
  `UnidadDeMedida` VARCHAR(45) NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`PK_CodigoDeUnidadDeMedidaBase`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_Tipo_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_Tipo_Producto` (
  `PK_Id_Tipo_Pro` INT NOT NULL,
  `Tipo_Producto` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_Id_Tipo_Pro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_Producto` (
  `PK_Codigo_Producto` INT NOT NULL,
  `FK_GrupoProductos` INT NOT NULL,
  `FK_Marca` INT NOT NULL,
  `FK_Moneda` INT(11) NOT NULL,
  `FK_UnidadDeMedida` INT NOT NULL,
  `FK_Tipo_Producto` INT NOT NULL,
  `Descripcion_Producto` VARCHAR(30) NOT NULL,
  `cargo_Producto` INT NOT NULL,
  `cargo_Acumulado_Producto` INT NOT NULL,
  `abono_Producto` INT NOT NULL,
  `abono_Acumulado_Producto` INT NOT NULL,
  `saldo_Actual` INT NOT NULL,
  `saldo_Anterior` INT NOT NULL,
  `Precio` DOUBLE NOT NULL,
  `costo` DOUBLE NOT NULL,
  `estatus` INT NOT NULL,
  PRIMARY KEY (`PK_Codigo_Producto`, `FK_GrupoProductos`, `FK_Moneda`, `FK_UnidadDeMedida`, `FK_Tipo_Producto`),
  INDEX `fk_Producto_Grupo_de_Productos1_idx` (`FK_GrupoProductos` ASC),
  INDEX `fk_Producto_marca_idx` (`FK_Marca` ASC),
  INDEX `fk_TBL_Producto_UnidadDeMedidaBase1_idx` (`FK_UnidadDeMedida` ASC),
  INDEX `fk_TBL_Producto_TBL_Tipo_Producto1_idx` (`FK_Tipo_Producto` ASC),
  CONSTRAINT `fk_Producto_Grupo_de_Productos1`
    FOREIGN KEY (`FK_GrupoProductos`)
    REFERENCES `BdColchoneria`.`TBL_Grupo_de_Productos` (`PK_Codigo_Grupo_de_Productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_marca`
    FOREIGN KEY (`FK_Marca`)
    REFERENCES `BdColchoneria`.`TBL_Modelo` (`PK_id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Producto_UnidadDeMedidaBase1`
    FOREIGN KEY (`FK_UnidadDeMedida`)
    REFERENCES `BdColchoneria`.`TBL_unidaddemedidabase` (`PK_CodigoDeUnidadDeMedidaBase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Producto_TBL_Tipo_Producto1`
    FOREIGN KEY (`FK_Tipo_Producto`)
    REFERENCES `BdColchoneria`.`TBL_Tipo_Producto` (`PK_Id_Tipo_Pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_Bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_Bodega` (
  `PK_Codigo_bodega` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Bodega` VARCHAR(45) NULL,
  `Encargado` VARCHAR(45) NULL,
  `Tipo_Bodega` VARCHAR(45) NULL,
  `Ubicacion_Bodega` VARCHAR(45) NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`PK_Codigo_bodega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_Vehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_Vehiculos` (
  `PK_id_Vehiculos` INT NOT NULL AUTO_INCREMENT,
  `Color` VARCHAR(45) NULL,
  `Modelo` INT NOT NULL,
  `FK_Modelo` INT NOT NULL,
  `FK_GrupoProductos` INT NOT NULL,
  `estatus` INT NOT NULL,
  PRIMARY KEY (`PK_id_Vehiculos`, `FK_Modelo`, `FK_GrupoProductos`),
  INDEX `fk_TBL_Vehiculos_TBL_Marca1_idx` (`FK_Modelo` ASC),
  INDEX `fk_TBL_Vehiculos_TBL_Grupo_de_Productos1_idx` (`FK_GrupoProductos` ASC),
  CONSTRAINT `fk_TBL_Vehiculos_TBL_Marca1`
    FOREIGN KEY (`FK_Modelo`)
    REFERENCES `BdColchoneria`.`TBL_Modelo` (`PK_id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Vehiculos_TBL_Grupo_de_Productos1`
    FOREIGN KEY (`FK_GrupoProductos`)
    REFERENCES `BdColchoneria`.`TBL_Grupo_de_Productos` (`PK_Codigo_Grupo_de_Productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_Marca` (
  `PK_id_Linea` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) NOT NULL,
  `Serie` VARCHAR(30) NOT NULL,
  `Año` DATE NOT NULL,
  `FK_Modelo` INT NOT NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`PK_id_Linea`),
  INDEX `FK_idmarca_idx` (`FK_Modelo` ASC),
  CONSTRAINT `FK_idmarca`
    FOREIGN KEY (`FK_Modelo`)
    REFERENCES `BdColchoneria`.`TBL_Modelo` (`PK_id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_Sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_Sede` (
  `PK_id_Sede` INT NOT NULL AUTO_INCREMENT,
  `Direccion` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`PK_id_Sede`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_Operaciones_Inv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_Operaciones_Inv` (
  `PK_Opc_inventario` INT NOT NULL,
  `Tipo_Operacion_Inv` INT NULL,
  `Id_Cuenta` INT NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`PK_Opc_inventario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_Enc_Doc_Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_Enc_Doc_Inventario` (
  `PK_Enc_Doc_Inventario` INT NOT NULL,
  `FK_Opc_inventario` INT NOT NULL,
  `fecha` DATE NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`PK_Enc_Doc_Inventario`, `FK_Opc_inventario`),
  INDEX `fk_TBL_Enc_Doc_Inventario_TBL_Operaciones_Inv1_idx` (`FK_Opc_inventario` ASC),
  CONSTRAINT `fk_TBL_Enc_Doc_Inventario_TBL_Operaciones_Inv1`
    FOREIGN KEY (`FK_Opc_inventario`)
    REFERENCES `BdColchoneria`.`TBL_Operaciones_Inv` (`PK_Opc_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_EncaInventarioBodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_EncaInventarioBodega` (
  `PK_Cod_Enca` INT NOT NULL,
  `FK_Codigo_bodega` INT NOT NULL,
  `Enca_Fecha` DATE NOT NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`PK_Cod_Enca`, `FK_Codigo_bodega`),
  INDEX `fk_TBL_EncaInventarioBodega_TBL_Bodega1_idx` (`FK_Codigo_bodega` ASC),
  CONSTRAINT `fk_TBL_EncaInventarioBodega_TBL_Bodega1`
    FOREIGN KEY (`FK_Codigo_bodega`)
    REFERENCES `BdColchoneria`.`TBL_Bodega` (`PK_Codigo_bodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_DetalleInventarioBodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_DetalleInventarioBodega` (
  `PK_DetalleInventarioBodega` INT NOT NULL,
  `FK_Cod_Enca` INT NOT NULL,
  `FK_Codigo_Producto` INT NOT NULL,
  `FK_id_Sede` INT NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`PK_DetalleInventarioBodega`, `FK_Cod_Enca`, `FK_Codigo_Producto`, `FK_id_Sede`),
  INDEX `fk_TBL_InventarioBodega_TBL_Producto1_idx` (`FK_Codigo_Producto` ASC),
  INDEX `fk_TBL_DetalleInventarioBodega_TBL_EncaInventarioBodega1_idx` (`FK_Cod_Enca` ASC),
  INDEX `fk_TBL_DetalleInventarioBodega_TBL_Sede1_idx` (`FK_id_Sede` ASC),
  CONSTRAINT `fk_TBL_InventarioBodega_TBL_Producto1`
    FOREIGN KEY (`FK_Codigo_Producto`)
    REFERENCES `BdColchoneria`.`TBL_Producto` (`PK_Codigo_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_DetalleInventarioBodega_TBL_EncaInventarioBodega1`
    FOREIGN KEY (`FK_Cod_Enca`)
    REFERENCES `BdColchoneria`.`TBL_EncaInventarioBodega` (`PK_Cod_Enca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_DetalleInventarioBodega_TBL_Sede1`
    FOREIGN KEY (`FK_id_Sede`)
    REFERENCES `BdColchoneria`.`TBL_Sede` (`PK_id_Sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_Detalle_Doc_Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_Detalle_Doc_Inventario` (
  `FK_Enc_Doc_Inventario` INT NOT NULL,
  `FK_Codigo_Producto` INT NOT NULL,
  `FK_DetalleInventarioBodega` INT NOT NULL,
  `Cantidad_producto` INT NULL,
  `precio` DOUBLE NULL,
  `Total` DOUBLE NULL,
  `costo` DOUBLE NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`FK_Enc_Doc_Inventario`, `FK_Codigo_Producto`, `FK_DetalleInventarioBodega`),
  INDEX `fk_TBL_Doc_Inventario_TBL_Producto1_idx` (`FK_Codigo_Producto` ASC),
  INDEX `fk_TBL_Doc_Inventario_TBL_Enc_Doc_Inventario1_idx` (`FK_Enc_Doc_Inventario` ASC),
  INDEX `fk_TBL_Detalle_Doc_Inventario_TBL_DetalleInventarioBodega1_idx` (`FK_DetalleInventarioBodega` ASC),
  CONSTRAINT `fk_TBL_Doc_Inventario_TBL_Producto1`
    FOREIGN KEY (`FK_Codigo_Producto`)
    REFERENCES `BdColchoneria`.`TBL_Producto` (`PK_Codigo_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Doc_Inventario_TBL_Enc_Doc_Inventario1`
    FOREIGN KEY (`FK_Enc_Doc_Inventario`)
    REFERENCES `BdColchoneria`.`TBL_Enc_Doc_Inventario` (`PK_Enc_Doc_Inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Detalle_Doc_Inventario_TBL_DetalleInventarioBodega1`
    FOREIGN KEY (`FK_DetalleInventarioBodega`)
    REFERENCES `BdColchoneria`.`TBL_DetalleInventarioBodega` (`PK_DetalleInventarioBodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_OrdenDeCompraEncabezado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_OrdenDeCompraEncabezado` (
  `PK_NumeroOrden` INT NOT NULL,
  `NombreDelSolicitante` VARCHAR(55) NULL,
  `FechaDeOrden` DATE NULL,
  `FechaDeLaEntrega` DATE NULL,
  `EstadoDeAutorizacion` INT NULL,
  `estatus` INT NULL,
  `Total` DECIMAL NULL,
  PRIMARY KEY (`PK_NumeroOrden`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_OrdenDeCompraDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_OrdenDeCompraDetalle` (
  `PK_Codigo_DetalleOrdenDeCompra` INT NOT NULL,
  `Cantidad` INT NULL,
  `Subtotal` DECIMAL NULL,
  `FK_EncabezadoOrden` INT NOT NULL,
  `FK_Productos` INT NOT NULL,
  PRIMARY KEY (`PK_Codigo_DetalleOrdenDeCompra`, `FK_EncabezadoOrden`, `FK_Productos`),
  INDEX `fk_TBL_OrdenDeCompraDetalle_TBL_OrdenDeCompraEncabezado1_idx` (`FK_EncabezadoOrden` ASC),
  INDEX `fk_TBL_OrdenDeCompraDetalle_TBL_Producto1_idx` (`FK_Productos` ASC),
  CONSTRAINT `fk_TBL_OrdenDeCompraDetalle_TBL_OrdenDeCompraEncabezado1`
    FOREIGN KEY (`FK_EncabezadoOrden`)
    REFERENCES `BdColchoneria`.`TBL_OrdenDeCompraEncabezado` (`PK_NumeroOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_OrdenDeCompraDetalle_TBL_Producto1`
    FOREIGN KEY (`FK_Productos`)
    REFERENCES `BdColchoneria`.`TBL_Producto` (`PK_Codigo_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_OrdenDeDevolucionEncabezado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_OrdenDeDevolucionEncabezado` (
  `PK_NumeroOrden` INT NOT NULL,
  `NombreDelSolicitante` VARCHAR(55) NULL,
  `FechaDeOrden` DATE NULL,
  `EstadoDeAutorizacion` INT NULL,
  `Motivo` VARCHAR(55) NULL,
  `Total` DECIMAL NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`PK_NumeroOrden`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_OrdenDeDevolucionDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_OrdenDeDevolucionDetalle` (
  `PK_Codigo_DetalleOrdenDeDevolucion` INT NOT NULL,
  `Cantidad` INT NULL,
  `Subtotal` DECIMAL NULL,
  `FK_EncabezadoOrden` INT NOT NULL,
  `FK_Producto` INT NOT NULL,
  PRIMARY KEY (`PK_Codigo_DetalleOrdenDeDevolucion`, `FK_EncabezadoOrden`, `FK_Producto`),
  INDEX `fk_TBL_OrdenDeCompraDetalle_TBL_OrdenDeCompraEncabezado1_idx` (`FK_EncabezadoOrden` ASC),
  INDEX `fk_TBL_OrdenDeDevolucionDetalle_TBL_Producto1_idx` (`FK_Producto` ASC),
  CONSTRAINT `fk_TBL_OrdenDeCompraDetalle_TBL_OrdenDeCompraEncabezado10`
    FOREIGN KEY (`FK_EncabezadoOrden`)
    REFERENCES `BdColchoneria`.`TBL_OrdenDeDevolucionEncabezado` (`PK_NumeroOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_OrdenDeDevolucionDetalle_TBL_Producto1`
    FOREIGN KEY (`FK_Producto`)
    REFERENCES `BdColchoneria`.`TBL_Producto` (`PK_Codigo_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_CotizacionEncabezado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_CotizacionEncabezado` (
  `PK_NumeroDeCotizacion` INT NOT NULL,
  `NombreDelSolicitante` VARCHAR(55) NULL,
  `FechaDeOrden` DATE NULL,
  `Total` DECIMAL NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`PK_NumeroDeCotizacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_CotizacionDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_CotizacionDetalle` (
  `PK_Codigo_DetalleCotizacion` INT NOT NULL,
  `Cantidad` INT NULL,
  `Subtotal` DECIMAL NULL,
  `FK_EncabezadoCotizacion` INT NOT NULL,
  `FK_Producto` INT NOT NULL,
  PRIMARY KEY (`PK_Codigo_DetalleCotizacion`, `FK_EncabezadoCotizacion`, `FK_Producto`),
  INDEX `fk_TBL_OrdenDeCompraDetalle_TBL_OrdenDeCompraEncabezado1_idx` (`FK_EncabezadoCotizacion` ASC),
  INDEX `fk_TBL_CotizacionDetalle_TBL_Producto1_idx` (`FK_Producto` ASC),
  CONSTRAINT `fk_TBL_OrdenDeCompraDetalle_TBL_OrdenDeCompraEncabezado11`
    FOREIGN KEY (`FK_EncabezadoCotizacion`)
    REFERENCES `BdColchoneria`.`TBL_CotizacionEncabezado` (`PK_NumeroDeCotizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_CotizacionDetalle_TBL_Producto1`
    FOREIGN KEY (`FK_Producto`)
    REFERENCES `BdColchoneria`.`TBL_Producto` (`PK_Codigo_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_Respaldos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_Respaldos` (
  `PK_codigo_respaldo` INT NOT NULL,
  `Fecha` DATE NULL,
  PRIMARY KEY (`PK_codigo_respaldo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_Destino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_Destino` (
  `PK_correlativo_destino` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(80) NULL,
  `latitud` INT NULL,
  `longitud` INT NULL,
  PRIMARY KEY (`PK_correlativo_destino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_Ruta_Encabezado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_Ruta_Encabezado` (
  `PK_Correlativo_ruta` INT NOT NULL AUTO_INCREMENT,
  `vehiculo_id` INT NULL,
  `fecha_creacion` DATETIME NULL,
  `envio_id` INT NULL,
  `descripcion_ruta` VARCHAR(80) NULL,
  PRIMARY KEY (`PK_Correlativo_ruta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_Ruta_Detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_Ruta_Detalle` (
  `PK_ruta_detalle_correlativo` INT NOT NULL AUTO_INCREMENT,
  `id_encabezado` INT NULL,
  `destino_id` INT NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`PK_ruta_detalle_correlativo`),
  INDEX `fk_ruta_detalle_idx` (`id_encabezado` ASC),
  INDEX `fk_ruta_detalle_destino_idx` (`destino_id` ASC),
  CONSTRAINT `fk_ruta_detalle_encabezado`
    FOREIGN KEY (`id_encabezado`)
    REFERENCES `BdColchoneria`.`TBL_Ruta_Encabezado` (`PK_Correlativo_ruta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ruta_detalle_destino`
    FOREIGN KEY (`destino_id`)
    REFERENCES `BdColchoneria`.`TBL_Destino` (`PK_correlativo_destino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_Envio_Encabezado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_Envio_Encabezado` (
  `PK_Codigo_Encabezado_Envio` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Punto_origen` VARCHAR(45) NOT NULL,
  `FK_id_Sede` INT NOT NULL,
  `FK_correlativo_destino` INT NOT NULL,
  `FK_id_Vehiculos` INT NOT NULL,
  PRIMARY KEY (`PK_Codigo_Encabezado_Envio`, `FK_id_Sede`, `FK_correlativo_destino`, `FK_id_Vehiculos`),
  INDEX `fk_TBL_Envio_Encabezado_TBL_Sede1_idx` (`FK_id_Sede` ASC),
  INDEX `fk_TBL_Envio_Encabezado_TBL_Destino1_idx` (`FK_correlativo_destino` ASC),
  INDEX `fk_TBL_Envio_Encabezado_TBL_Vehiculos1_idx` (`FK_id_Vehiculos` ASC),
  CONSTRAINT `fk_TBL_Envio_Encabezado_TBL_Sede1`
    FOREIGN KEY (`FK_id_Sede`)
    REFERENCES `BdColchoneria`.`TBL_Sede` (`PK_id_Sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Envio_Encabezado_TBL_Destino1`
    FOREIGN KEY (`FK_correlativo_destino`)
    REFERENCES `BdColchoneria`.`TBL_Destino` (`PK_correlativo_destino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Envio_Encabezado_TBL_Vehiculos1`
    FOREIGN KEY (`FK_id_Vehiculos`)
    REFERENCES `BdColchoneria`.`TBL_Vehiculos` (`PK_id_Vehiculos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_Detalle_Envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_Detalle_Envio` (
  `PK_Codigo_Detalle_Envio` INT NOT NULL,
  `Descripcion_Producto` VARCHAR(45) NOT NULL,
  `No_Total_Productos` INT NOT NULL,
  `FK_Codigo_Producto` INT NOT NULL,
  `FK_Codigo_Encabezado` INT NOT NULL,
  PRIMARY KEY (`PK_Codigo_Detalle_Envio`, `FK_Codigo_Producto`, `FK_Codigo_Encabezado`),
  INDEX `fk_TBL_Detalle_Envio_TBL_Producto1_idx` (`FK_Codigo_Producto` ASC),
  INDEX `fk_TBL_Detalle_Envio_TBL_Envio_Encabezado1_idx` (`FK_Codigo_Encabezado` ASC),
  CONSTRAINT `fk_TBL_Detalle_Envio_TBL_Producto1`
    FOREIGN KEY (`FK_Codigo_Producto`)
    REFERENCES `BdColchoneria`.`TBL_Producto` (`PK_Codigo_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Detalle_Envio_TBL_Envio_Encabezado1`
    FOREIGN KEY (`FK_Codigo_Encabezado`)
    REFERENCES `BdColchoneria`.`TBL_Envio_Encabezado` (`PK_Codigo_Encabezado_Envio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_Historico_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_Historico_Producto` (
  `PK_Codigo_Producto` INT NOT NULL,
  `FK_GrupoProductos` INT NOT NULL,
  `FK_Marca` INT NOT NULL,
  `FK_Moneda` INT(11) NOT NULL,
  `FK_UnidadDeMedida` INT NOT NULL,
  `FK_Tipo_Producto` INT NOT NULL,
  `Descripcion_Producto` VARCHAR(30) NOT NULL,
  `cargo_Producto` INT NOT NULL,
  `cargo_Acumulado_Producto` INT NOT NULL,
  `abono_Producto` INT NOT NULL,
  `abono_Acumulado_Producto` INT NOT NULL,
  `saldo_Actual` INT NOT NULL,
  `saldo_Anterior` INT NOT NULL,
  `Precio` DOUBLE NOT NULL,
  `costo` DOUBLE NOT NULL,
  `estatus` INT NOT NULL,
  `TBL_Respaldos_PK_codigo_respaldo` INT NOT NULL,
  PRIMARY KEY (`PK_Codigo_Producto`, `FK_GrupoProductos`, `FK_Moneda`, `FK_UnidadDeMedida`, `FK_Tipo_Producto`),
  INDEX `fk_Producto_Grupo_de_Productos1_idx` (`FK_GrupoProductos` ASC),
  INDEX `fk_Producto_marca_idx` (`FK_Marca` ASC),
  INDEX `fk_TBL_Producto_UnidadDeMedidaBase1_idx` (`FK_UnidadDeMedida` ASC),
  INDEX `fk_TBL_Producto_TBL_Tipo_Producto1_idx` (`FK_Tipo_Producto` ASC),
  INDEX `fk_TBL_Historico_Producto_TBL_Respaldos1_idx` (`TBL_Respaldos_PK_codigo_respaldo` ASC),
  CONSTRAINT `fk_Producto_Grupo_de_Productos10`
    FOREIGN KEY (`FK_GrupoProductos`)
    REFERENCES `BdColchoneria`.`TBL_Grupo_de_Productos` (`PK_Codigo_Grupo_de_Productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_marca0`
    FOREIGN KEY (`FK_Marca`)
    REFERENCES `BdColchoneria`.`TBL_Modelo` (`PK_id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Producto_UnidadDeMedidaBase10`
    FOREIGN KEY (`FK_UnidadDeMedida`)
    REFERENCES `BdColchoneria`.`TBL_unidaddemedidabase` (`PK_CodigoDeUnidadDeMedidaBase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Producto_TBL_Tipo_Producto10`
    FOREIGN KEY (`FK_Tipo_Producto`)
    REFERENCES `BdColchoneria`.`TBL_Tipo_Producto` (`PK_Id_Tipo_Pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Historico_Producto_TBL_Respaldos1`
    FOREIGN KEY (`TBL_Respaldos_PK_codigo_respaldo`)
    REFERENCES `BdColchoneria`.`TBL_Respaldos` (`PK_codigo_respaldo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_Entrega_Producto_Historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_Entrega_Producto_Historial` (
  `PK_Correlativo_Producto_Historial` INT NOT NULL AUTO_INCREMENT,
  `Ruta_detalle_correlativo` INT NULL,
  `Codigo_Producto` INT NULL,
  PRIMARY KEY (`PK_Correlativo_Producto_Historial`),
  INDEX `ruta_detalle_historial_fk_idx` (`Ruta_detalle_correlativo` ASC),
  INDEX `codigo_producto_historial_fk_idx` (`Codigo_Producto` ASC),
  CONSTRAINT `ruta_detalle_historial_fk`
    FOREIGN KEY (`Ruta_detalle_correlativo`)
    REFERENCES `BdColchoneria`.`TBL_Ruta_Detalle` (`PK_ruta_detalle_correlativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codigo_producto_historial_fk`
    FOREIGN KEY (`Codigo_Producto`)
    REFERENCES `BdColchoneria`.`TBL_Producto` (`PK_Codigo_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_encabezado_poliza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_encabezado_poliza` (
  `id_Poliza` INT NOT NULL,
  `Fecha_Actual_Poliza` DATE NOT NULL,
  `Total_Poliza` FLOAT NULL,
  `estatus` INT NOT NULL,
  PRIMARY KEY (`id_Poliza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BdColchoneria`.`TBL_detalle_poliza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BdColchoneria`.`TBL_detalle_poliza` (
  `Id_Detalle_Poliza` INT NOT NULL,
  `Nombre_Cuenta_DP` VARCHAR(45) NULL,
  `Cargo_detalle_poliza` FLOAT NULL,
  `Abono_detalle_poliza` FLOAT NULL,
  `id_poliza` INT NOT NULL,
  PRIMARY KEY (`Id_Detalle_Poliza`),
  INDEX `fk_TBL_detalle_poliza_TBL_encabezado_poliza1_idx` (`id_poliza` ASC),
  CONSTRAINT `fk_TBL_detalle_poliza_TBL_encabezado_poliza1`
    FOREIGN KEY (`id_poliza`)
    REFERENCES `BdColchoneria`.`TBL_encabezado_poliza` (`id_Poliza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
